include: package:very_good_analysis/analysis_options.yaml

language:
  strict-inference: false

linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    inference_failure_on_function_invocation: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**.g.dart
